
Traceback (most recent call last):
  File "tests/exceptions/source/others/exception_formatting_function.py", line 14, in a
    1 / 0
ZeroDivisionError: division by zero

Traceback (most recent call last):

  File "tests/exceptions/source/others/exception_formatting_function.py", line 14, in a
    1 / 0

ZeroDivisionError: division by zero

Traceback (most recent call last):
> File "tests/exceptions/source/others/exception_formatting_function.py", line 17, in <module>
    a()
  File "tests/exceptions/source/others/exception_formatting_function.py", line 14, in a
    1 / 0
ZeroDivisionError: division by zero

Traceback (most recent call last):

> File "tests/exceptions/source/others/exception_formatting_function.py", line 17, in <module>
    a()
    â”” <function a at 0xDEADBEEF>

  File "tests/exceptions/source/others/exception_formatting_function.py", line 14, in a
    1 / 0

ZeroDivisionError: division by zero
